### ISSUE TITLE
Closed Solid Field not making the wall where its placed to become "Grided"

### ISSUE THREAD

**Issue by LautaroL20** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#10]
![20170106112538_1](https://cloud.githubusercontent.com/assets/12244376/21720621/f51d278e-d402-11e6-82fb-b10aa536630a.jpg)

**Comment by vrad-exe** [comment]
The Gridded Wall item can be used for this, but it should still be done automatically.

**Comment by vrad-exe** [comment]
This issue was moved to BEEmod/BEE2-items#1521
