### ISSUE TITLE
A few BP notes

### ISSUE THREAD

**Issue by Byzarru** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#13]
1. P2 Style fire cubes should use an orange ring instead of a blue ring.
2. Old Aperture variants of special cubes should have specially colored corners. The faces should be printed/painted with whichever emblem is on their BP counterparts.
3. Blue Portals signages will be appended to the BEESigns item or made into a new Blue Portal Signs item, depending on which and how many new items are implemented. 
4. I will begin retexturing of the signage items (Connections and BEE especially) for BPDC style. Some icons are colored (Will color fizzlers, fire, energy). 
5. Soundtrack should be packaged, like with Rexaura.
6. Music cubes should have matching music cube receptacles (determined by Button type). 
7. Music cubes should have different tracks for each style, each two or four measures long (I might be able to make those sounds, I'll post them if I do)
8. Wall cutout tiles should create the stone surfaces as seen in some chambers.

**Comment by Byzarru** [comment]
Also, Fire, Ice, and Light cubes should be bundled with Button Type.

**Comment by TheDarkBomber** [comment]
I can use 5 cubes in one package, using the Cube Select. (Standard = Fire, Companion = Ice, Redirection = Fizzle-Proof, Sphere = Activation, and Frankencube = Light)

**Comment by Byzarru** [comment]
Activation should be by itself; none of the other cubes connect to an output. Replace it with the Heavy Cube.

**Comment by vrad-exe** [comment]
@Byzarru - What would the Heavy Cube do? The only thing I could think of is destroying Breakable Glass when set on top of it, and that doesn't seem very useful.

**Comment by vrad-exe** [comment]
@TheDarkBomber - You don't need to make each item a separate package - just have `bpItems`, `bpStyle`, and `bpMusic`.

**Comment by TheDarkBomber** [comment]
@Luke18033 The Heavy Cube is a cube that cannot be picked up by the player. This can be moved by the fan and portals. It would also break breakable glass. It can also be moved by excursion funnels. This is considered a BP item as it was part of a wall texture.

**Comment by vrad-exe** [comment]
Make the "Reflection" type the Light Cube, so that the laser preview will appear.

**Comment by Byzarru** [comment]
The Light Cube doesn't work like a Reflection Cube. It absorbs light rather than redirects it.

**Comment by TheDarkBomber** [comment]
It still looks like a reflection cube..

**Comment by vrad-exe** [comment]
The third Cube Type option always shows a laser emitting from the cube in the editor, which would be useful for the Light Cube.

**Comment by TheDarkBomber** [comment]
* Fire = Standard
* Ice = Companion
* Light = Reflection
* Fizzle-Proof = Sphere
* Heavy = Frankenturret
* Activator = Separate item

Also, I found a "Clock" cube texture in the game files...

**Comment by vrad-exe** [comment]
The clock cube actually appears a couple of times, but it can't be reached. I think it also appears in the "cube list" on the wall.

**Comment by SP2G50000** [comment]
The clock cube was used in Blue Portal's time trials
The normal cubes are replaced with these cubes, I don't think it adds anything

**Comment by Byzarru** [comment]
There isn't much use for them, from what I've seen.

**Comment by vrad-exe** [comment]
It could be used for a timed activator cube...

**Comment by vrad-exe** [comment]
Also, because of the way cubes are generated you'd need to implement [this](https://github.com/BEEmod/BEE2-items/issues/95#issuecomment-284753804) for the BP cubes.

**Comment by vrad-exe** [comment]
This issue was moved to BEEmod/BEE2-items#2139.
