### ISSUE TITLE
BPDC Style Notes

### ISSUE THREAD

**Issue by TheDarkBomber** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#14]
Notes for the BPDC Style:

* The Entrance Room would be a standard room that has a blue portal open, which leads to the entrance corridor.

* The exit room would be a corridor that leads to a door, that leads to the entrance room, but the blue portal is closed.

* The materials can be found in the game files for Blue Portals. Unportalable walls will use the stone texture, and Decorations would add white tiles on the walls. Portalable walls will be an orange version of P1 walls, as seen in the game.

* I would like @TeamSpen210 to develop this.

**Comment by vrad-exe** [comment]
I don't think BPDC Voicelines could be added, for the same reason as P1 GLaDOS.

**Comment by TheDarkBomber** [comment]
What was the reason?

**Comment by Byzarru** [comment]
> Wall cutout tiles should create the stone surfaces as seen in some chambers.

...once those are developed. There are already smooth wall surfaces, the stone walls are just for decoration. And there should be a way to add the blue accents above the stone.

**Comment by TeamSpen210** [comment]
The reason for voice lines is that it's not possible to add translated versions, and you can't add closed captions either.

**Comment by vrad-exe** [comment]
@TheDarkBomber - Since @TeamSpen210 doesn't seem to be developing the style, why don't you try to figure out how to make styles and develop it yourself?

**Comment by vrad-exe** [comment]
This issue was moved to BEEmod/BEE2-items#2139
