### ISSUE TITLE
Light Cubes

### ISSUE THREAD

**Issue by Byzarru** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#15]
They charge when hit by light and emit light until the charge wears off.
![20170111232507_1](https://cloud.githubusercontent.com/assets/22107242/21878183/27dbb30a-d856-11e6-8b7e-2f09ea4ef13b.jpg)
![20170111232514_1](https://cloud.githubusercontent.com/assets/22107242/21878184/27e51e86-d856-11e6-869c-a6a521a04c5d.jpg)
![20170111232530_1](https://cloud.githubusercontent.com/assets/22107242/21878185/28305ea0-d856-11e6-995a-ffc7d5394084.jpg)

**Comment by TheDarkBomber** [comment]
Where did you get this?

**Comment by Byzarru** [comment]
It comes with the extended play mappack. Test chamber 2.

**Comment by TheDarkBomber** [comment]
Ok

**Comment by vrad-exe** [comment]
For Portal 2 styles, this should be a purple reflection cube.
