### ISSUE TITLE
Ladders

### ISSUE THREAD

**Issue by Byzarru** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#16]
They are a bit buggy in-game, but they (usually) let players climb upwards.
![20170111225610_1](https://cloud.githubusercontent.com/assets/22107242/21878204/5ae155ca-d856-11e6-8e64-d8d08614d8d7.jpg)
![20170111225834_1](https://cloud.githubusercontent.com/assets/22107242/21878205/5ae38aa2-d856-11e6-8d1d-7811c8f33780.jpg)
![20170111225909_1](https://cloud.githubusercontent.com/assets/22107242/21878206/5ae590f4-d856-11e6-92e1-a9d06094a83f.jpg)

**Comment by Luke18033** [comment]
From what I've played, ladders don't work correctly in Portal 2.

**Comment by vrad-exe** [comment]
Unfortunately, ladders don't work in Portal 2.
