### ISSUE TITLE
BP Variant Checklist

### ISSUE THREAD

**Issue by TheDarkBomber** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#18]
### Cube Catcher
- [x] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
- [ ] Overgrown
### Fire Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
### Magnet (Pull/Push/Float)
- [ ] Clean/P1/BPDC
- [ ] Old Aperture
### Water
- [ ] Standard
- [ ] Overgrown
### Fizzle-Proof Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
### Ice Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
### Light (emitters)
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
- [ ] BTS
### Eye (light capture device)
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
- [ ] BTS
### Mirror
- [ ] Standard
- [ ] Overgrown
### Activation Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
### Red Flow (visual panels)
- [ ] P1/BPDC
- [ ] Clean
- [ ] Overgrown
- [ ] Old Aperture
### Light Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
### Heavy Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
### Music Cube
- [ ] P1/BPDC
- [ ] Clean
- [ ] Old Aperture
## BPDC Variants of standard items
- [ ] Pedestal Button
- [ ] Weighted Storage Cube
- [ ] Gel Droppers (should use the ones in Conversion Cubed)
- [ ] Button
- [ ] FDF
- [ ] Signage
- [ ] Goo (Coolant)

**Comment by Byzarru** [comment]
New revelation: Gel is known in the files as 'coolant'.

**Comment by vrad-exe** [comment]
Red Flow should be placed like fizzlers, extending to the opposite wall. The 6-position handle wouldn't be present, however.

**Comment by vrad-exe** [comment]
BP is now moved to BEE2-items, and a variant checklist isn't really necessary, case closed.
