### ISSUE TITLE
Cube Catcher not appearing

### ISSUE THREAD

**Issue by Byzarru** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#20]
![20170222185743_1](https://cloud.githubusercontent.com/assets/22107242/23241184/4de60ecc-f937-11e6-9ce7-0a19e568ac61.jpg)
It could be that this is overgrown and the style likes to act funny, but...
![20170222185756_1](https://cloud.githubusercontent.com/assets/22107242/23241195/58d49fec-f937-11e6-972f-cab81325d8c5.jpg)
This is in the same map.

**Comment by TheDarkBomber** [comment]
I don't know why it would be not appearing.

**Comment by vrad-exe** [comment]
Portal 2 styles should use a Clean dropper model.

**Comment by Luke18033** [comment]
*dropper

**Comment by Luke18033** [comment]
I hate swipe typing.

**Comment by TheDarkBomber** [comment]
That won't work. We'll just change the base texture.

**Comment by vrad-exe** [comment]
This issue was moved to BEEmod/BEE2-items#2140
