### ISSUE TITLE
Portal 1 Physics Shield and Closed Solid Field unstyled

### ISSUE THREAD

**Issue by vrad-exe** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#4]
- [x] Physics Repulsion Field styled for P1
- [x] Closed Solid Field styled for P1

---

![20161206114650_1](https://cloud.githubusercontent.com/assets/19228201/20941073/c62d6e64-bba9-11e6-9f03-76eafddf1ec5.jpg)
![20161206114602_1](https://cloud.githubusercontent.com/assets/19228201/20941120/f5df526c-bba9-11e6-86d4-999dcbb4209a.jpg)

**Comment by Luke18033** [comment]
Also can I be a collaborator so I can add labels?

**Comment by vrad-exe** [comment]
@TheDarkBomber Did you style the Physics Repulsion Field?
