### ISSUE TITLE
Physics Repulsion Field still shows sparks even when it is off

### ISSUE THREAD

**Issue by vrad-exe** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#5]
When the Physics Repulsion Field is off, sparks will still show when a physics object touches where it previously was. Physics objects can still be carried through.

UPDATE: This happens on all styles

I would actually like these sparks to be removed, the original didn't have this.

**Comment by TheDarkBomber** [comment]
The sparks were a feature that @TeamSpen210 added.

**Comment by vrad-exe** [comment]
That's not the point of this issue.

**Comment by vrad-exe** [comment]
I actually don't like the sparks. The original version didn't have it, and neither do any of the other physics object-blocking fizzlers.
