### ISSUE TITLE
Old Aperture Physics Repulsion Field unstyled

### ISSUE THREAD

**Issue by vrad-exe** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#6]
Closed Solid Field *is* styled, however.

**Comment by TheDarkBomber** [comment]
I styled it.

**Comment by TheDarkBomber** [comment]
Try using 50s

**Comment by vrad-exe** [comment]
Nope, still not styled.

**Comment by vrad-exe** [comment]
@TeamSpen210 fixed this.

**Comment by TeamSpen210** [comment]
You needed to specify it in `info.txt`, so the BEE knows the `retro` folder is for `BEE_1950s`.
