### ISSUE TITLE
Closed Solid Field Editor Model inside framgent from the frames using wrong colour

### ISSUE THREAD

**Issue by LautaroL20** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#8]
It is posible to fix this by decompiling the editor mdl file:

![20170106110646_1](https://cloud.githubusercontent.com/assets/12244376/21720294/05242ca6-d401-11e6-8149-c1a7b170e31e.jpg)

**Comment by TeamSpen210** [comment]
You don't need to decompile. This folder in [resource-src](https://github.com/BEEmod/resource-src/tree/master/models/editor/fizzlers) contains the source model files for this editor model. Make a copy of one of the QCs, then edit the names inside and run `studioMDL` to get a new model file.

**Comment by vrad-exe** [comment]
This issue was moved to BEEmod/BEE2-items#1522
