### ISSUE TITLE
In-game closed solid field model using wrong coloured frame

### ISSUE THREAD

**Issue by LautaroL20** [TheDarkBomber/BEE2-items-TheDarkBomber-Contributions#9]
![20170106110306_1](https://cloud.githubusercontent.com/assets/12244376/21720422/c9442820-d401-11e6-8c1e-97a2d6d9108e.jpg)

**Comment by TheDarkBomber** [comment]
I fixed it, but it will need to be commited. In order for this, I will need to be collaborator.

**Comment by LautaroL20** [comment]
Just send the updated files to me or @Luke18033 and we will commit it.

**Comment by TheDarkBomber** [comment]
No, I will need to be collaborator.

**Comment by LautaroL20** [comment]
You don´t really need to be one as long as you give your files to any of us via zippyshare or any other server...

BTW: Personally i don´t mind having any of your files, you can keep them forever. I just wanted to help a bit commiting it for you.

**Comment by TheDarkBomber** [comment]
Just talk to @TeamSpen210

**Comment by vrad-exe** [comment]
@TheDarkBomber Can't you do that?

**Comment by TheDarkBomber** [comment]
@Luke18033 You asking him would really help as well.

**Comment by Luke18033** [comment]
Why would I ask to make the person who kept deleting everything I make a collaborator? If you want to be one, ask him yourself.

**Comment by TheDarkBomber** [comment]
\>:(

**Comment by LautaroL20** [comment]
> the person who kept deleting everything I make

Don´t forget he was also fiddling all the labels, that was annoyng as hell.....

**Comment by TeamSpen210** [comment]
That's what a fork is for... merge in the changes from upstream, then commit your changes and do a pull request.

**Comment by TheDarkBomber** [comment]
I already have a pull request open. Plus I need to update the commits here.

**Comment by TheDarkBomber** [comment]
These have been committed now.
